version: "3.6"

services:
  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.0.0"
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-network

  blog:
    container_name: blog
    image: "blog:latest"
    ports:
      - "8080:8080"
    environment:
      ES_HOSTNAME: elasticsearch
      ES_PASSWORD: password
      ADMIN_PASSWORD: password

    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - es-network

networks:
  es-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
