server:
  port: 8080

spring:
  security:
    user:
      password: ${ADMIN_PASSWORD:password}

  elasticsearch:
    rest:
      uris:
        - http://elasticsearch:9200
      username: elastic
      password: ${ES_PASSWORD:password}
